# Generated by Django 4.2.4 on 2023-10-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_studylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='thestart_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
