# Generated by Django 4.2.6 on 2023-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_usersettings_wallpaper_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='wallpaper_name',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='wallpaper_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
