# Generated by Django 4.2.6 on 2023-10-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_usersettings_wallpaper_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='thestart_date',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='wallpaper_number',
        ),
    ]
