# Generated by Django 4.2.6 on 2023-10-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_usersettings_thestart_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='wallpaper_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
